# Exercicis de Numpy

- Tots els exercicis d'aquesta secció s'han d'implementar utilitzant la biblioteca `numpy`.
- La gran majoria dels exercicis es poden resoldre **sense** cap bucle `for` o `while`, només utilitzant les funcions de Numpy o operacions vectoritzades.
- La gran majoria dels exercicis es poden resoldre amb un màxim d'1-6 línies de codi.
- Si no saps com resoldre alguna cosa, no dubtis a buscar a Internet sobre el teu problema. Per exemple, `"Com ordenar un array en Numpy?"`.
- És millor que no facis servir ChatGPT per trobar la solució, així t'acostumes a programar amb `numpy`.

In [1]:
import numpy as np

## Zeros

Inicialitza un vector nul (amb zeros) de longitud 20.

In [3]:
vector_nuls = np.zeros(20, dtype=int)

print(vector_nuls)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


## Inicialització de matriu

Inicialitza una matriu nul·la (amb zeros) de mida 3x2.

In [5]:
matriu_de_nuls = np.zeros((3, 2), dtype=int)
matriu_de_nuls

array([[0, 0],
       [0, 0],
       [0, 0]])

## Reemplaçar

Reemplaça l'element mínim d'un vector aleatori per un 0.

In [8]:
vector = np.random.randint(1, 100, size=10)
print("Vector original:", vector)

vector[np.argmin(vector)] = 0

print("Vector modificat:", vector)

Vector original: [76 80 50 30 56 30 46 90 40 13]
Vector modificat: [76 80 50 30 56 30 46 90 40  0]


## Consecutius

Crea un vector amb tots els valors consecutius entre 12 i 38.

In [18]:
consecutius = np.arange(12, 39)
print("consecutius:", consecutius)

consecutius: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


## Inicialització de vector

Inicialitza un vector de longitud 10 amb nombres enters aleatoris entre 1 i 20.

In [74]:
vector_aleatori = np.random.randint(1, 21, size=10)
print("Vector aleatori:", vector_aleatori)

Vector aleatori: [14 11 19 14 19  5 18  8 15 14]


a) Filtra els elements que són més grans que 3 i més petits que 12.

In [77]:
print("Vector original:     ", vector_aleatori)

elements_filtrats = vector_aleatori[(vector_aleatori > 3) & (vector_aleatori < 12)]

print("Elements filtrats:   ", elements_filtrats)

Vector original:      [14 11 19 14 19  5 18  8 15 14]
Elements filtrats:    [11  5  8]


b) Filtra els elements que són menors o iguals a 5 o més grans que 15.

## Matriu aleatòria

Crea una matriu 4x4 amb nombres enters aleatoris entre 0 i 5.

## No zero

Troba els índexs dels elements que no són 0 al vector: [2, 1, 0, 0, 3, 1, 0].

In [ ]:
v = np.array([2, 1, 0, 0, 3, 1, 0])

## Envoltar

Crea una matriu 10x10 amb zeros a dins i uns que els envoltin, com la següent:

```
[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]
```

## Reemplaçar per zero

Defineix una funció que, donat un vector, retorni tots els elements més grans que 10 reemplaçats per 0.

Exemple: [4, 7, 15, 21, 3, 34] → [4, 7, 0, 0, 3, 0]

## Negar

Defineix una funció que negui (canviï el signe) de tots els elements d'un vector amb valors entre 2 i 6 (incloent també els valors negatius entre -6 i -2).

Exemple: [4, 7, -6, 21, 3, 34] → [-4,  7, 6, 21, -3, 34]

In [ ]:
def vec(v):
    return v[v != 0]

## Matriu de negatius

Donada una matriu que conté tant nombres positius com negatius, modifica-la perquè:
- Cada **nombre positiu** es mantingui igual.
- Cada **nombre negatiu** es reemplaci per la suma de tots els nombres positius de la mateixa columna.

Per exemple, aquesta matriu:

```
np.array([
    [ 5, -2,  3],
    [-1,  4, -6],
    [ 2, -3,  1]
])
```

esdevé:

```
np.array([
    [5, 4, 3],
    [7, 4, 4],
    [2, 4, 1]
])
```

Nota: La funció `np.where()` pot ser molt útil.

In [ ]:
m = np.array([
    [ 5, -2,  3],
    [-1,  4, -6],
    [ 2, -3,  1]
])

## Més proper

Defineix una funció `closest(v, n)` que, donat un vector i un nombre $N$, retorni l'element més proper a $N$. En cas d'empat, retorna qualsevol d'aquests elements.

In [3]:
def closest(v,n):
    idx = np.abs(v - n).argmin()
    return v[idx]

In [4]:
# Els propers "tests" haurien de passar un cop definida la funció

assert closest([1, 2, 3, 4], 2) == 2
assert closest([1, 2, 3, 4], 5) == 4
assert closest([1, 2, 3, 4], -3) == 1
assert closest([1, 2, 2, 3, 4], 2) == 2
assert closest([1, 2, 2, 3, 4], 2.4) == 2
assert closest([1, 2, 2, 3, 4], 2.6) == 3

TypeError: unsupported operand type(s) for -: 'list' and 'int'

## N-Més grans

Defineix una funció que, donat un nombre positiu $N$ i un vector, retorni els $N$ elements més grans del vector. Pots suposar que $N$ és més petit que la longitud del vector.

## Únics

Crea un vector aleatori de longitud 20 amb valors entre 1 i 8. Quins elements únics (sense repetició) s'han creat?

##  Codificació one-hot

Implementa una funció que retorni una matriu amb la codificació one-hot d'un vector.

Codificació one-hot: https://www.datacamp.com/tutorial/one-hot-encoding-python-tutorial

- Exemple:
    - Entrada: [0, 2, 1, 2, 0, 1]
    - Sortida:
```
[[1., 0., 0.],
[0., 0., 1.],
[0., 1., 0.],
[0., 0., 1.],
[1., 0., 0.],
[0., 1., 0.]]
```

## Escalat Min-Max

Implementa una funció `minmax_scale(values)` que reescali una llista (o array de NumPy) de valors numèrics de manera que tots els valors estiguin dins del rang **[0, 1]**. Concretament, el nombre més petit tindrà el valor de $0$, mentre que el més gran tindrà el valor de $1$. La resta de nombres es trobaran entremig.

Aquest tipus de normalització és habitual en aprenentatge automàtic, ja que assegura que totes les característiques contribueixen de manera equitativa al procés d'entrenament d'un model, independentment de la seva escala original.

Donat un array de valors $X$, la fórmula d'escalat Min-Max per a cadascun dels seus valors $x_i$ és:

$x_i\_scaled = (x_i - min(X)) / (max(X) - min(X))$



## Fruit Ninja

Ets un mestre de Fruit Ninja, tallant fruites amb precisió. Has tallat 100 fruites, cadascuna t'ha donat una puntuació aleatòria entre 1 i 100. No obstant això, gràcies a una tècnica ninja, cada tercera puntuació es duplica. Calcula la teva puntuació total.

## Extraterrestres

Els extraterrestres estan transmetent missatges binaris — arrays de 100 elements que contenen només 0s i 1s.

No obstant això, el seu missatge real està amagat dins del senyal: sempre comença i acaba amb 1, i tot el que hi ha abans del primer 1 i després de l'últim 1 és només soroll.

Per exemple, donat el missatge `[0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0]`, el missatge real que has d'extreure és el rang des del primer 1 fins a l'últim, ambdós inclosos `[1, 0, 1, 1, 0, 0, 1]`.

In [5]:
# Funció que genera un missatge aleatori d'extraterrestres

def get_aliens_message():
    # Es crea un missatge on la majoria són zeros
    message = np.zeros(100, dtype=int)

    # S'introdueix el missatge real
    start_index = np.random.randint(10, 40)
    end_index = np.random.randint(60, 90)

    message[start_index:end_index] = np.random.randint(2, size=end_index-start_index)
    message[start_index] = 1
    message[end_index] = 1
    return message

In [6]:
message = get_aliens_message()

In [7]:
message

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Max Pooling

A les xarxes neuronals convolucionals (CNN), utilitzades per al processament d'imatges, hi ha un pas anomenat max pooling. Ajuda a reduir la mida d'una matriu (sovint una imatge) tot mantenint només la informació més important — el valor màxim dins de petites regions.

Escriu una funció `max_pooling(matrix)` que faci max pooling 2×2 sobre una matriu donada. És a dir, per a cada regió 2×2, agafa el valor màxim i afegeix-lo a una nova matriu. Finalment, retorna la matriu resultant més petita.

Si la matriu d'entrada té dimensions $m · n$, la matriu resultant tindrà dimensions $(m−1) · (n−1)$.

Per exemple, per a la matriu d'entrada

[

    [1, 3, 2, 4]

    [5, 6, 1, 0]

    [2, 8, 3, 1]

    [4, 7, 2, 5]
],

la matriu resultant de l'operació de max pooling és

[
   
    [6 6 4]

    [8 8 3]

    [8 8 5]
]

**Explicació**:
- La funció va lliscant una finestra 2×2 d'un pas en pas.
- Per a la regió superior esquerra de 2×2 que conté els valors 1, 3, 5 i 6, el valor màxim és 6. Això dona el primer valor a la part superior esquerra de la matriu retornada.
- Això es repeteix per tota la matriu per a cada regió 2×2.

In [22]:
matrix = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 0],
    [2, 8, 3, 1],
    [4, 7, 2, 5],
])

## El joc de la vida

Implementa "El joc de la vida" utilitzant Numpy.